# nginx.conf

# This block contains global settings related to worker processes.

events {
    # Empty because the default settings are sufficient for this example.
}

http {

    # Defines a group of backend servers.
    # NGINX will distribute incoming requests between them
    # using round-robin by default.
    upstream my_backend_servers {
        server backend1:5000;
        server backend2:5000;
    }

    # Defines an HTTP server.
    server {

        # Listen for incoming HTTP requests on port 80
        # INSIDE the container.
        #
        # The compose file maps:
        # Host:8080 -> Container:80
        listen 80;

        # Match every request.
        location / {

            # Forward the request to the backend group.
            proxy_pass http://backend_servers;

            # Forward the original Host header.
            proxy_set_header Host $host;

            # Forward the client's IP address.
            proxy_set_header X-Real-IP $remote_addr;

            # Preserve the chain of client IPs if multiple proxies exist.
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Tell the backend whether the original request
            # was HTTP or HTTPS.
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}